# Generated by Django 3.1.2 on 2020-12-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videoapp', '0006_auto_20201201_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to=''),
        ),
    ]
