# Generated by Django 3.1.2 on 2020-12-01 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Videoapp', '0008_auto_20201201_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='URL',
        ),
    ]
