# Generated by Django 3.1.2 on 2021-02-17 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Videoapp', '0009_remove_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.TextField(max_length=50),
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj', models.TextField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Videoapp.video')),
            ],
        ),
    ]
