# Generated by Django 3.1.2 on 2021-02-22 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Videoapp', '0010_auto_20210221_2021'),
        ('Videoapp', '0010_auto_20210217_1648'),
    ]

    operations = [
    ]
