# Generated by Django 3.1.2 on 2021-02-23 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Videoapp', '0011_merge_20210222_1736'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Object',
            new_name='VideoObject',
        ),
    ]
