# Generated by Django 3.1.2 on 2021-02-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videoapp', '0012_auto_20210223_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoobject',
            name='obj',
            field=models.JSONField(),
        ),
    ]
