# Generated by Django 3.1.7 on 2021-07-06 23:30

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Videoapp', '0016_auto_20210706_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='Videos'),
        ),
    ]
