# Generated by Django 3.1.7 on 2021-07-07 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Videoapp', '0017_auto_20210706_2330'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
