# Generated by Django 3.1.2 on 2021-02-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
